### ISSUE TITLE
Se genera el docker sin problemas, pero al arrancar da error:

### ISSUE THREAD

**Issue by InfraGllen** [DemocraciaEnRed/participes-app#66]
# Comportamiento observado
Se generó el docker con docker compose . y ahora si genera los contenedores sin problemas.

# Capturas de pantalla
[sumenGllen.log](https://github.com/user-attachments/files/17234199/sumenGllen.log)

**Comment by mpvaldez** [comment]
Gracias por el aviso!
podrías enviar la configuración que estas colocando en el `docker-compose.yml`?

**Comment by InfraGllen** [comment]
Va el archivo. Lo único que le agregué fue la persistencia en /opt/persist (en este lugar ha creado los archivos del mysql sin problemas).
Antes de mandarte esto hice la prueba de bajar el selinux (por las dudas), pero el error persiste.
Archivos docker-compose-yml
```
services:
  app: &app
    build: .
    image: democraciaenred/participes-app:testing
    environment:
      APP_ENV: staging
      APP_NAME: Participes
      APP_DEBUG: 'true'
      APP_URL: http://localhost
      NOCAPTCHA_SECRET: 
      NOCAPTCHA_SITEKEY: 
      MAPBOX_API_KEY: 
      MAPBOX_MAP_STYLE: 
      CONTAINER_ROLE: app
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      QUEUE_CONNECTION: redis
      REDIS_CLIENT: predis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_QUEUE: mailer,default
      MAIL_MAILER: smtp
      MAIL_HOST: 
      MAIL_PORT: 
      MAIL_USERNAME:
      MAIL_PASSWORD: 
      MAIL_ENCRYPTION: 
      MAIL_FROM_ADDRESS:
      MAIL_FROM_NAME: 
    volumes:
      - public_dir:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - 9000:9000
    depends_on:
      - 'nginx'
      - 'mysql'
      - 'redis'
    restart: unless-stopped
    networks:
      - participes

  nginx:
    image: nginx
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - type: volume
        source: public_dir
        target: /var/www/html
        volume:
          nocopy: true
      - type: bind
        source: ./docker/nginx/conf.d/app.conf
        target: /etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - participes

  # queue:
  #   <<: *app

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - participes

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 31415926
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - /opt/persist:/var/lib/mysql
    restart: unless-stopped
    networks:
      - participes

volumes:
  public_dir:
  redis:

networks:
  participes:
    driver: bridge
```
